library(indianabirdtracker)
library(curl)
root <- tempfile("bird-tracker-")
dir.create(root)
db <- file.path(root, "birds.duckdb")
photos <- file.path(root, "photos")
refs <- file.path(root, "references")
app <- indianabirdtracker::run_app(db_path = db, photo_library = photos, reference_path = refs)
port <- httpuv::randomPort()
server <- shiny::runApp(app, port = port, launch.browser = FALSE, quiet = TRUE)
on.exit(server$stop(), add = TRUE)
Sys.sleep(2)
response <- curl_fetch_memory(paste0("http://127.0.0.1:", port))
if (response$status_code != 200) stop("Shiny smoke check returned HTTP ", response$status_code)
message("Shiny smoke check passed.")
